--------------------------------------------------------
--  File created - Friday-January-18-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DBV_CONNECTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBVIEWS"."DBV_CONNECTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DBV_GRAPH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBVIEWS"."DBV_GRAPH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DBV_HTML_BLOCK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBVIEWS"."DBV_HTML_BLOCK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DBV_TABLE_FIELD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBVIEWS"."DBV_TABLE_FIELD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DBV_TABLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBVIEWS"."DBV_TABLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DBV_VIEW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBVIEWS"."DBV_VIEW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DBV_CONNECTION
--------------------------------------------------------

  CREATE TABLE "DBVIEWS"."DBV_CONNECTION" 
   (	"ID" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"URL" VARCHAR2(4000 BYTE), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DBV_GRAPH
--------------------------------------------------------

  CREATE TABLE "DBVIEWS"."DBV_GRAPH" 
   (	"ID" NUMBER(10,0), 
	"VIEW_ID" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"LABEL" VARCHAR2(255 BYTE), 
	"SQL_QUERY" VARCHAR2(4000 BYTE), 
	"TAB_INDEX" NUMBER(10,0) DEFAULT '0', 
	"GRAPH_TYPE" VARCHAR2(50 BYTE) DEFAULT 'pie', 
	"SERIE_COLUMN" VARCHAR2(255 BYTE) DEFAULT NULL, 
	"XAXIS_COLUMN" VARCHAR2(255 BYTE), 
	"YAXIS_COLUMN" VARCHAR2(255 BYTE), 
	"XMODE" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"YMODE" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"WIDTH" NUMBER(10,0) DEFAULT '400', 
	"HEIGHT" NUMBER(10,0) DEFAULT '400', 
	"LEGEND_POSITION" VARCHAR2(50 BYTE) DEFAULT 'ne', 
	"FILTER_POSITION" VARCHAR2(50 BYTE) DEFAULT 'ne', 
	"TOOLBAR_POSITION" VARCHAR2(50 BYTE) DEFAULT 'ne', 
	"CSV_SEPARATOR" VARCHAR2(20 BYTE) DEFAULT '|'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DBV_HTML_BLOCK
--------------------------------------------------------

  CREATE TABLE "DBVIEWS"."DBV_HTML_BLOCK" 
   (	"ID" NUMBER(10,0), 
	"VIEW_ID" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"LABEL" VARCHAR2(255 BYTE), 
	"SQL_QUERY" VARCHAR2(4000 BYTE), 
	"TAB_INDEX" NUMBER(10,0) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DBV_TABLE
--------------------------------------------------------

  CREATE TABLE "DBVIEWS"."DBV_TABLE" 
   (	"ID" NUMBER(10,0), 
	"VIEW_ID" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"LABEL" VARCHAR2(255 BYTE), 
	"SQL_QUERY" VARCHAR2(4000 BYTE), 
	"TAB_INDEX" NUMBER(10,0) DEFAULT '0', 
	"FILTER_POSITION" VARCHAR2(50 BYTE) DEFAULT 'top', 
	"SQL_QUERY_INDEX" VARCHAR2(255 BYTE), 
	"TOOLBAR_POSITION" VARCHAR2(50 BYTE) DEFAULT 'bottom', 
	"CSV_SEPARATOR" VARCHAR2(20 BYTE) DEFAULT '|'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DBV_TABLE_FIELD
--------------------------------------------------------

  CREATE TABLE "DBVIEWS"."DBV_TABLE_FIELD" 
   (	"ID" NUMBER(10,0), 
	"TABLE_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"COLUMN_NAME" VARCHAR2(64 BYTE), 
	"TYPE" NUMBER(10,0) DEFAULT '12', 
	"WIDTH" VARCHAR2(8 BYTE) DEFAULT NULL, 
	"ALIGN" VARCHAR2(8 BYTE) DEFAULT NULL, 
	"VALIGN" VARCHAR2(8 BYTE) DEFAULT NULL, 
	"FIELD_ORDER" VARCHAR2(8 BYTE) DEFAULT NULL, 
	"VISIBLE" VARCHAR2(8 BYTE) DEFAULT NULL, 
	"EXPORTABLE" VARCHAR2(8 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DBV_VIEW
--------------------------------------------------------

  CREATE TABLE "DBVIEWS"."DBV_VIEW" 
   (	"ID" NUMBER(10,0), 
	"CONNECTION_ID" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"AUTH_PRINCIPALS" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"JQUI_PLUGIN" VARCHAR2(50 BYTE) DEFAULT 'tabs', 
	"JQUI_PLUGIN_OPTIONS" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"LAZY_LOAD" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DBV_CONNECTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBVIEWS"."DBV_CONNECTION_PK" ON "DBVIEWS"."DBV_CONNECTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DBV_GRAPH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBVIEWS"."DBV_GRAPH_PK" ON "DBVIEWS"."DBV_GRAPH" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007133
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBVIEWS"."SYS_C007133" ON "DBVIEWS"."DBV_VIEW" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007140
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBVIEWS"."SYS_C007140" ON "DBVIEWS"."DBV_HTML_BLOCK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007147
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBVIEWS"."SYS_C007147" ON "DBVIEWS"."DBV_TABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007153
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBVIEWS"."SYS_C007153" ON "DBVIEWS"."DBV_TABLE_FIELD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger DBV_CONNECTION_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBVIEWS"."DBV_CONNECTION_SEQ_TR" 
 BEFORE INSERT ON dbv_connection FOR EACH ROW
  WHEN (NEW.id IS NULL) BEGIN
 SELECT dbv_connection_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "DBVIEWS"."DBV_CONNECTION_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DBV_GRAPH_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBVIEWS"."DBV_GRAPH_SEQ_TR" 
 BEFORE INSERT ON dbv_graph FOR EACH ROW
  WHEN (NEW.id IS NULL) BEGIN
 SELECT dbv_graph_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "DBVIEWS"."DBV_GRAPH_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DBV_HTML_BLOCK_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBVIEWS"."DBV_HTML_BLOCK_SEQ_TR" 
 BEFORE INSERT ON dbv_html_block FOR EACH ROW
  WHEN (NEW.id IS NULL) BEGIN
 SELECT dbv_html_block_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "DBVIEWS"."DBV_HTML_BLOCK_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DBV_TABLE_FIELD_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBVIEWS"."DBV_TABLE_FIELD_SEQ_TR" 
 BEFORE INSERT ON dbv_table_field FOR EACH ROW
  WHEN (NEW.id IS NULL) BEGIN
 SELECT dbv_table_field_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "DBVIEWS"."DBV_TABLE_FIELD_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DBV_TABLE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBVIEWS"."DBV_TABLE_SEQ_TR" 
 BEFORE INSERT ON dbv_table FOR EACH ROW
  WHEN (NEW.id IS NULL) BEGIN
 SELECT dbv_table_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "DBVIEWS"."DBV_TABLE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DBV_VIEW_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBVIEWS"."DBV_VIEW_SEQ_TR" 
 BEFORE INSERT ON dbv_view FOR EACH ROW
  WHEN (NEW.id IS NULL) BEGIN
 SELECT dbv_view_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "DBVIEWS"."DBV_VIEW_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table DBV_CONNECTION
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_CONNECTION" ADD CONSTRAINT "DBV_CONNECTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBVIEWS"."DBV_CONNECTION" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_CONNECTION" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_CONNECTION" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_CONNECTION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_CONNECTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DBV_GRAPH
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("CSV_SEPARATOR" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("LEGEND_POSITION" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("TOOLBAR_POSITION" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("FILTER_POSITION" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" ADD CONSTRAINT "DBV_GRAPH_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("HEIGHT" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("WIDTH" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("GRAPH_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("TAB_INDEX" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("SQL_QUERY" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("LABEL" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("VIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_GRAPH" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DBV_HTML_BLOCK
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_HTML_BLOCK" ADD CONSTRAINT "DBV_HTML_BLOCK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBVIEWS"."DBV_HTML_BLOCK" MODIFY ("TAB_INDEX" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_HTML_BLOCK" MODIFY ("SQL_QUERY" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_HTML_BLOCK" MODIFY ("LABEL" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_HTML_BLOCK" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_HTML_BLOCK" MODIFY ("VIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_HTML_BLOCK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DBV_TABLE
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_TABLE" MODIFY ("CSV_SEPARATOR" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE" MODIFY ("TOOLBAR_POSITION" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE" MODIFY ("FILTER_POSITION" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE" ADD CONSTRAINT "DBV_TABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBVIEWS"."DBV_TABLE" MODIFY ("TAB_INDEX" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE" MODIFY ("SQL_QUERY" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE" MODIFY ("LABEL" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE" MODIFY ("VIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DBV_TABLE_FIELD
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_TABLE_FIELD" ADD CONSTRAINT "DBV_TABLE_FIELD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBVIEWS"."DBV_TABLE_FIELD" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE_FIELD" MODIFY ("COLUMN_NAME" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE_FIELD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE_FIELD" MODIFY ("TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_TABLE_FIELD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DBV_VIEW
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_VIEW" MODIFY ("LAZY_LOAD" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_VIEW" ADD CONSTRAINT "DBV_VIEW_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBVIEWS"."DBV_VIEW" MODIFY ("JQUI_PLUGIN" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_VIEW" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_VIEW" MODIFY ("CONNECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "DBVIEWS"."DBV_VIEW" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DBV_GRAPH
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_GRAPH" ADD CONSTRAINT "DBV_GRAPH_FK_VIEW" FOREIGN KEY ("VIEW_ID")
	  REFERENCES "DBVIEWS"."DBV_VIEW" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DBV_HTML_BLOCK
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_HTML_BLOCK" ADD CONSTRAINT "DBV_HTML_BLOCK_FK_VIEW" FOREIGN KEY ("VIEW_ID")
	  REFERENCES "DBVIEWS"."DBV_VIEW" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DBV_TABLE
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_TABLE" ADD CONSTRAINT "DBV_TABLE_FK_VIEW" FOREIGN KEY ("VIEW_ID")
	  REFERENCES "DBVIEWS"."DBV_VIEW" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DBV_TABLE_FIELD
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_TABLE_FIELD" ADD CONSTRAINT "DBV_TABLE_FIELD_FK_TABLE" FOREIGN KEY ("TABLE_ID")
	  REFERENCES "DBVIEWS"."DBV_TABLE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DBV_VIEW
--------------------------------------------------------

  ALTER TABLE "DBVIEWS"."DBV_VIEW" ADD CONSTRAINT "DBV_VIEW_FK_CONNECTION" FOREIGN KEY ("CONNECTION_ID")
	  REFERENCES "DBVIEWS"."DBV_CONNECTION" ("ID") ON DELETE CASCADE ENABLE;
